Repository creation guidelines
ska-telescope/developer.skatelescope.org pull request #27
Opened 2019-04-09 12:30 UTC by flyingfrog81

This PR includes all the documentation related to the creation of new repositories.

2019-04-09 12:31 UTC, flyingfrog81 commented
This is a first stub and I'm welcome to iterate based on this version. Please push straight into the branch if you see fit.

2019-04-09 13:24 UTC, Matteo04052017 commented on src/projects/create_new_project.rst
> +  *All software and firmware source code handed over to the SKA organisation shall be organised into source code repositories. A source code repository is a set of files and metadata, organized in a
Well, there is a difference between component and module. 
I agree on source code repositories that map to individual applications or modules but those are not components. 
In tango-controls, a component is a device or a device server and if we go for this definition then we will end up with too many repositories. The more repositories we have, the more complicated the integration would be. 
I would prefer to have one repository per module and for each module one team.

2019-04-09 13:27 UTC, Matteo04052017 requested changes
I would change the rule for creating a repository... the map should be 1 Module - 1 Repository where the module is what you assign to a particular team.

2019-04-29 13:29 UTC, flyingfrog81 commented
I would say that this could be Many modules one Repo, as long as the modules expose a self-included behavior.

2019-05-02 08:41 UTC, flyingfrog81 commented
Merging this as no feedback is provided

2019-05-02 08:41 UTC, merged